MySite/Models/SiteImages.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MySite.Models
{
    public class SiteImages
    {
        public int SiteImagesId { get; set; }
        public int ContentDataId { get; set; }
        public string Image_url { get; set; }
        public string Name { get; set; }
    }
}

MySite/Controllers/API/EditController.cs
using MySite.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;


namespace MySite.Controllers.API
{
    public class EditController : ApiController
    {
        [HttpGet]
        [Route("api/Test")]
        public string Test()
        {
            return "Success - 123";
        }

        [HttpPost]
        [Route("api/CreateContent")]       
        public APIActionResult CreateContent()
        {
            #region Parms



            //get CategoryId
            int contentDataId = -1;
            try
            {
                if (!Int32.TryParse(HttpContext.Current.Request.Form["ContentDataId"].ToString(), out contentDataId))
                {
                    contentDataId = -1;
                }
            }
            catch (Exception ex) { }


            //get CategoryId
            int categoryId;
            if (!Int32.TryParse(HttpContext.Current.Request.Form["CategoryId"].ToString(), out categoryId))
            {
                return ReturnResult("nvalid parameter CategoryId", false, -1);
            }

            //get Title
            string title = HttpContext.Current.Request.Form["Title"].ToString();
            if (string.IsNullOrEmpty(title))
            {
                return ReturnResult("invalid parameter Title", false, -1);
            }

            //get Title
            string urlString = HttpContext.Current.Request.Form["URLString"].ToString();
            if (string.IsNullOrEmpty(urlString))
            {
                return ReturnResult("invalid parameter URLString", false, -1);
            }


            string content = HttpContext.Current.Request.Form["Content"].ToString();

            StringWriter myWriter = new StringWriter();
            HttpUtility.HtmlDecode(content, myWriter);
            content = myWriter.ToString();

            #endregion Parms

            using (var db = new ApplicationDbContext())
                {
                if (contentDataId == -1)
                {
                    ContentData cd = new ContentData
                    {
                        CategoryId = categoryId,
                        Title = title,
                        URLString = urlString,
                        Content = content,
                    };

                    db.ContentDatas.Add(cd);
                    db.SaveChanges();
                    return ReturnResult("Created", true, cd.ContentDataId);
                }
                else
                {
                    var caQuery = db.ContentDatas.Where(x => x.ContentDataId == contentDataId);
                    if (!caQuery.Any())
                    {
                        return ReturnResult("Invalid data", false, -1);
                    }

                    ContentData cd = caQuery.Single();
                    cd.CategoryId = categoryId;
                    cd.Title = title;
                    cd.URLString = urlString;
                    cd.Content = content;
                    db.SaveChanges();
                    return ReturnResult("Updated", true, cd.ContentDataId);
                }
            }
        }

        public APIActionResult ReturnResult(string Message, bool Success, int ItemID)
        {
            APIActionResult res = new APIActionResult
            {
                Message = Message,
                ItemID = ItemID,
                Success = Success
            };

            return res;
        }
    }

    public class APIActionResult
    {
        public int ItemID { get; set; }
        public string Message { get; set; }
        public bool Success { get; set; }
    }
}

MySite/Controllers/SiteImagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MySite.Models;

namespace MySite.Controllers
{
    public class SiteImagesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //GET: SiteImages/ImageList
        public JsonResult ImageList(int ContentDataId)
        {
            return Json(db.SiteImages.Where(img => img.ContentDataId == ContentDataId).ToList(), JsonRequestBehavior.AllowGet);
        }

        // GET: SiteImages
        public ActionResult Index()
        {
            return View(db.SiteImages.ToList());
        }

        // GET: SiteImages/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SiteImages siteImages = db.SiteImages.Find(id);
            if (siteImages == null)
            {
                return HttpNotFound();
            }
            return View(siteImages);
        }

        // GET: SiteImages/Create
        public ActionResult Create()
        {            
           return View();
        }


        [HttpPost]
        public ActionResult UploadNewImage(FormCollection fc, HttpPostedFileBase file)
        {
            int ContentDataId;
            if (!int.TryParse(fc["ContentDataId"], out ContentDataId))
            {
                ContentDataId = 1;
            }


            var fileName = Path.GetFileName(file.FileName);
            var ext = Path.GetExtension(file.FileName);
            var allowedExtensions = new[] { ".jpg", ".png", ".jpg", ".jpeg" };
            if (allowedExtensions.Contains(ext.ToLower())) //check what type of extension  
            {
                string name = Path.GetFileNameWithoutExtension(fileName); //getting file name without extension  
                string filePath = name + "_" + ContentDataId + ext; //appending the name with id  
                                                                    // store the file inside ~/project folder(Img)  
                var path = Path.Combine(Server.MapPath("~/Img"), filePath);
                file.SaveAs(path);

                SiteImages siteImages = new SiteImages();
                siteImages.ContentDataId = ContentDataId;
                siteImages.Image_url = filePath;
                siteImages.Name = fc["Name"].ToString();

                //if (fileName)
                {
                    db.SiteImages.Add(siteImages);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            else
            {

            }

            return View();
        }

        [HttpPost]
        public ActionResult Editmage(FormCollection fc, HttpPostedFileBase file)
        {
            int SiteImagesId;
            if (!int.TryParse(fc["SiteImagesId"], out SiteImagesId))
            {
                throw new HttpException(404, "Image not found");
            }

            int ContentDataId;
            if (!int.TryParse(fc["ContentDataId"], out ContentDataId))
            {
                throw new HttpException(404, "ContentDataId not found");
            }

            SiteImages siteImages = db.SiteImages.Find(SiteImagesId);

            if ( file != null )
            {
                var fileName = Path.GetFileName(file.FileName);
                var ext = Path.GetExtension(file.FileName);
                var allowedExtensions = new[] { ".jpg", ".png", ".jpg", ".jpeg" };
                if (allowedExtensions.Contains(ext.ToLower()))
                {
                    string name = Path.GetFileNameWithoutExtension(fileName); //getting file name without extension  
                    string filePath = name + "_" + ContentDataId + ext; //appending the name with id  
                                                                        // store the file inside ~/project folder(Img)  
                    var path = Path.Combine(Server.MapPath("~/Img"), filePath);
                    file.SaveAs(path);

                    siteImages.Image_url = filePath;
                }
            }

            siteImages.ContentDataId = ContentDataId;
            siteImages.Name = fc["Name"].ToString();
            db.SaveChanges();
           

            return View();

        }


        // POST: SiteImages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SiteImagesId,ContentDataId,Image_url,Name")] SiteImages siteImages)
        {
            if (ModelState.IsValid)
            {
                db.SiteImages.Add(siteImages);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(siteImages);
        }

        // GET: SiteImages/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SiteImages siteImages = db.SiteImages.Find(id);
            if (siteImages == null)
            {
                return HttpNotFound();
            }
            return View(siteImages);
        }

        // POST: SiteImages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SiteImagesId,ContentDataId,Image_url,Name")] SiteImages siteImages)
        {
            if (ModelState.IsValid)
            {
                db.Entry(siteImages).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(siteImages);
        }

        // GET: SiteImages/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SiteImages siteImages = db.SiteImages.Find(id);
            if (siteImages == null)
            {
                return HttpNotFound();
            }
            return View(siteImages);
        }

        // POST: SiteImages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SiteImages siteImages = db.SiteImages.Find(id);
            db.SiteImages.Remove(siteImages);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MySite/Views/SiteImages/Create.cshtml
@model MySite.Models.SiteImages

@using (Html.BeginForm("UploadNewImage", "SiteImages", FormMethod.Post
                        , new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>SiteImages1</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label class="control-label col-md-2">Image</label>
            <div class="col-md-10">
                <img id="user_img" height="100" width="90" style="border:solid" />
                <input type="file" title="search image" id="file" name="file" onchange="show(this)" />
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.ContentDataId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContentDataId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContentDataId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image_url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image_url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image_url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/JavaScript">

        $(document).ready(function () {
            debugger;
            var ContentDataId = GetQueryStringParams("ContentDataId");
            $('#ContentDataId').val(ContentDataId);
        });

        function GetQueryStringParams(sParam) {
            var sPageURL = window.location.search.substring(1);
            var sURLVariables = sPageURL.split('&');
            for (var i = 0; i < sURLVariables.length; i++) {
                var sParameterName = sURLVariables[i].split('=');
                if (sParameterName[0] == sParam) {
                    return sParameterName[1];
                }
            }
        }

        function show(input) {
            if (input.files && input.files[0]) {
                //debugger;
                $('#txt_name').val(input.files[0].name);
                var filerdr = new FileReader();
                filerdr.onload = function (e) {
                    $('#user_img').attr('src', e.target.result);
                }
                filerdr.readAsDataURL(input.files[0]);
            }
        }
    </script>
}

MySite/Views/SiteImages/Delete.cshtml
@model MySite.Models.SiteImages

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SiteImages</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ContentDataId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContentDataId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image_url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image_url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MySite/Views/SiteImages/Details.cshtml
@model MySite.Models.SiteImages

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SiteImages</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ContentDataId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContentDataId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image_url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image_url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SiteImagesId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MySite/Views/SiteImages/Edit.cshtml
@model MySite.Models.SiteImages

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Editmage", "SiteImages", FormMethod.Post
                        , new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SiteImagesId)

        <div class="form-group">
            <label class="control-label col-md-2">Image</label>
            <div class="col-md-10">
                <img id="user_img" height="100" width="90" style="border:solid"  />
                <input type="file" title="search image" id="file" name="file" onchange="show(this)" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContentDataId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContentDataId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContentDataId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image_url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image_url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image_url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/JavaScript">

        $(document).ready(function () {            
             $("#user_img").attr("src", "/Img/" + "@Html.Raw(Model.Image_url)");            
        });

        function GetQueryStringParams(sParam) {
            var sPageURL = window.location.search.substring(1);
            var sURLVariables = sPageURL.split('&');
            for (var i = 0; i < sURLVariables.length; i++) {
                var sParameterName = sURLVariables[i].split('=');
                if (sParameterName[0] == sParam) {
                    return sParameterName[1];
                }
            }
        }

        function show(input) {
            if (input.files && input.files[0]) {
                //debugger;
                $('#txt_name').val(input.files[0].name);
                var filerdr = new FileReader();
                filerdr.onload = function (e) {
                    $('#user_img').attr('src', e.target.result);
                }
                filerdr.readAsDataURL(input.files[0]);
            }
        }

    </script>
}

MySite/Views/SiteImages/Index.cshtml
@model IEnumerable<MySite.Models.SiteImages>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ContentDataId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image_url)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ContentDataId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Image_url)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.SiteImagesId }) |
            @Html.ActionLink("Details", "Details", new { id=item.SiteImagesId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.SiteImagesId })
        </td>
    </tr>
}

</table>